name: Publish 1.0 docs

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  publish-docs:
    # runs on main repo only
    if: github.repository == 'apache/pekko-persistence-jdbc'
    name: Publish
    runs-on: ubuntu-22.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          fetch-tags: true
          ref: 1.0.x

      - name: Setup Java 8
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 8

      - name: Build Documentation
        run: |-
          sbt "set ThisBuild / version := \"1.0.0\"; docs/paradox; unidoc"

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-persistence-jdbc/1.0.0/
          mkdir -p target/nightly-docs/docs/pekko-persistence-jdbc/1.0/
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-persistence-jdbc/1.0.0/docs
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-persistence-jdbc/1.0/docs
          rm -r docs/target/paradox/site/main/
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-persistence-jdbc/1.0.0/api
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-persistence-jdbc/1.0/api
          rm -r target/scala-2.13/unidoc

      - name: Upload 1.0.x docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-persistence-jdbc/1.0.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

      - name: Upload 1.0 docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-persistence-jdbc/1.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
