name: Publish 1.0 Nightly

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  publish10:
    if: github.repository == 'apache/pekko-persistence-jdbc'
    name: Publish
    runs-on: ubuntu-22.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          fetch-tags: true
          ref: 1.0.x

      - name: Setup Java 8
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 8

      - name: Publish Jars to Apache Maven Repository
        run: |-
          sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
