name: Publish Nightly

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "23 0 * * *"

jobs:
  publish:
    # runs on main repo only
    if: github.repository == 'apache/pekko-persistence-jdbc'
    name: Publish
    runs-on: ubuntu-22.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Java 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Publish Jars to Apache Maven Repository
        run: |-
          sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}

      - name: Build Documentation
        run: |-
          sbt docs/paradox unidoc

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create nightly directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-persistence-jdbc/${{ github.ref_name }}-snapshot/
          mv docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-persistence-jdbc/${{ github.ref_name }}-snapshot/docs
          mv target/scala-2.13/unidoc target/nightly-docs/docs/pekko-persistence-jdbc/${{ github.ref_name }}-snapshot/api

      - name: Upload nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-persistence-jdbc/${{ github.ref_name }}-snapshot # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
