name: Publish 1.2 Nightly

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  publish12:
    if: github.repository == 'apache/pekko-persistence-jdbc'
    name: Publish
    runs-on: ubuntu-22.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          fetch-tags: true
          ref: 1.2.x

      - name: Setup Java 8
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: temurin
          java-version: 8

      - name: Publish Jars to Apache Maven Repository
        run: |-
          sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
